title: 庶民样本

theme: ./themes/luna

theme_config:
  header_title: e.z.
  nav:
    - title: about
      link: /about
    - title: girls
      link: /girls
    - title: donate
      link: /donate
  website: https://github.com/egoist
  repo: egoist/blog
  twitter: _egoistlily

markdown:
  slugify: limax
  plugins:
    - name: markdown-it-footnote

ga_id: UA-54857209-6